language: elixir
elixir:
  - 1.10
otp_release:
  - 22.0
matrix:
  include:
    - elixir: 1.9
      otp_release: 21.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
  - cd installer && mix deps.get
  - cd .. && nvm install 12.16 && nvm use 12.16
script:
  - MIX_ENV=test mix coveralls.json
  - cd installer && MIX_ENV=test elixir -S mix coveralls.json
  - cd ../assets && npm install && npm test:coverage
  - cd .. && bash <(curl -s https://codecov.io/bash)
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
cache:
  directories:
  - assets/node_modules
